added swagger-ui and described all endpoints
Broscorp-net/community-tools pull request #161
Opened 2020-09-20 12:41 UTC by fugrusha

2020-10-01 07:43 UTC, pesua requested changes
Чот у меня не получилось зайти в юайку, нопмни, она в http://localhost:8080/swagger-ui/? Кажется, для этого надо было еще добавить конфиги для статических файлов.

На этом проекте мы комитим в ветку основного репозитория и делаем пулл из неё, а не из своего репозитория. Мне прищлось повозиться чтоб завести твой код локально, а так бы просто свичнул ветку.

2020-10-01 07:43 UTC, pesua commented on src/main/java/com/community/tools/controller/GitHubController.java
> +          @ApiImplicitParam(name = "start", dataType = "string",
dataType и paramType нельзя оставить с дефолтными значениями?

2020-10-01 16:59 UTC, fugrusha commented on src/main/java/com/community/tools/controller/GitHubController.java
> +          @ApiImplicitParam(name = "start", dataType = "string",
1. URL: http://localhost:8080/swagger-ui.html - в конце .html
2. Можно, убрал

2020-10-04 07:47 UTC, pesua approved these changes
Айс, добавь в readme.md пару слов про свагер и путь к странице и мерджи..

2020-10-10 12:25 UTC, fugrusha commented
Обновил свой мастер и решил все мерд конфликты

2020-10-10 13:22 UTC, merged