New check gh login
Broscorp-net/community-tools pull request #162
Opened 2020-09-22 15:07 UTC by likeRewca

Вкратце как должно теперь "работать":
Шаг 1)(перед вводом логина гита)
*So, that’s it. You've read through all our rules.
*If you're ready to accept this challenge enter your GitHub nickname.
*"likeRewca"(это пример с моим логином)
*Okay! Let me check your nick, likeRewca
Тут если нет такого логина выведет следующие (то что я временно вывожу)
*Sry but looks like you are not registered on Github :worried:
Шаг 2)Если же все ок, то будет проверка "на дурака". Ему/ей присылается ссылка в его гит и ему/ей нужно подтвердить является это их профилем.
*Please tell me is that you? (yes/no)
*"https://github.com/likeRewca"
*yes / no
Если no, то переходит к шагу 1, а если yes то продолжает.
Шаг 3) Записывает в базу, добавляет в колобораторы (в роль trainee). 
Да сразу выдается роль и выводится сообщение:
Hurray! Your nick is available. Nice to meet you :smile:

2020-09-25 09:34 UTC, pesua commented
Hello world!

2020-09-30 16:42 UTC, pesua requested changes
Все текстовки надо вынести в файлы свойств и перевести их на один язык.

2020-09-30 16:42 UTC, pesua commented on src/main/java/com/community/tools/model/StateEntity.java
> +    @Column(name="user_id")
Зачем это? Чем плохи дефолты?

2020-09-30 16:42 UTC, pesua commented on src/main/java/com/community/tools/service/PublishWeekStatsService.java
> +    slackService.sendMessageToConversation("test_3", messageBuilder.toString());
Когда мы захотим поменять имя надо будет все перекомпилировать и передеплоивать, это не айс.
Сделай это свойством, пожалуйста.

2020-09-30 16:42 UTC, pesua commented on src/main/java/com/community/tools/service/github/AddMentorService.java
> +          .sendMessageToConversation("test_3", "User " + user + " create a pull request \n url: " + url
То же самое.
+ литералы не должны повторяться, когда захотим поменять имя канала то надо будет лазить по коду и везде его искать, прикинь какой это будет ад?

2020-09-30 16:42 UTC, pesua commented on src/main/java/com/community/tools/service/github/AddMentorService.java
> +          .sendMessageToConversation("test_3", "User " + user + " create a pull request \n url: " + url
И глагол не верно используется в сообщении). Вообще лучше сообщения тоже из свойств подтягивать.

2020-09-30 16:42 UTC, pesua commented on src/main/java/com/community/tools/service/github/GitHubHookServlet.java
> +                .sendMessageToConversation("test_3", "User " + user + " create a pull request \n url: " + url);
То же

2020-09-30 16:42 UTC, pesua commented on src/main/java/com/community/tools/service/slack/SlackHandlerService.java
> +              }else if (teamJoinPayload.getEvent().getText().equals("no")) {
Недоформатировано

2020-09-30 16:42 UTC, pesua commented on src/main/java/com/community/tools/util/statemachie/actions/AddGitNameAction.java
> +      slackService.sendMessageToConversation("test3",
Вот тут уже другое имя используется. Это же ошибка?

2020-09-30 16:42 UTC, pesua commented on src/main/java/com/community/tools/util/statemachie/actions/AddGitNameAction.java
> +    SimpleDateFormat format = new SimpleDateFormat("E yyyy.MM.dd 'в' hh:mm:ss a zzz");
Разве у сообщения и так не будет таймстампа?

2020-09-30 16:42 UTC, pesua commented on src/main/java/com/community/tools/util/statemachie/actions/DidNotPassVerificationGitLogin.java
> +          "Lets try again! \nWrite your nike again.");
И человек второй раз введет ту же последовательность символов). Надо сообщить ему причину ошибки.

2020-09-30 16:42 UTC, pesua commented on src/main/java/com/community/tools/util/statemachie/actions/HideGuard.java
>        try {
Трайкетч а в трайкетче это как-то плохо.

2020-09-30 16:42 UTC, pesua commented on src/test/java/com/community/tools/util/statemachie/actions/AddGitNameActionTest.java
> +  public void tearDown() throws Exception {
Зачем нужен этот метод?

2020-09-30 16:42 UTC, pesua commented on src/test/java/com/community/tools/util/statemachie/actions/AddGitNameActionTest.java
> +    addGitNameAction.execute(stateContext);
Тут не хватает проверок

2020-09-30 16:42 UTC, pesua commented on src/test/java/com/community/tools/util/statemachie/actions/HideGuardTest.java
> +  public void tearDown() throws Exception {
То же

2020-09-30 16:42 UTC, pesua commented on src/test/java/com/community/tools/util/statemachie/actions/HideGuardTest.java
> +@Sql(value = "/test.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
Разве у нас не автогенерация схемы?

2020-09-30 16:42 UTC, pesua commented on src/test/resources/test.sql
> +/*select * from "public".state_entity;*/
Нельзя закоменченный код использовать.

2020-09-30 18:10 UTC, likeRewca commented on src/main/java/com/community/tools/util/statemachie/actions/DidNotPassVerificationGitLogin.java
> +          "Lets try again! \nWrite your nike again.");
заменил сообщение на - "Ok, if it's not you, then let's try to re-write your login."
И это не ошибка, это событие возникающее при ответе "no" во время ввода логина GH. По сути он пишет no и переводит в состояние где он снова должен ввести логин.

2020-09-30 18:27 UTC, likeRewca commented on src/main/java/com/community/tools/util/statemachie/actions/HideGuard.java
>        try {
У нас 2 стула или так как есть или "SneakyThrows"

2020-09-30 18:46 UTC, likeRewca commented on src/test/java/com/community/tools/util/statemachie/actions/HideGuardTest.java
> +@Sql(value = "/test.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
это тут лишнее

2020-09-30 18:49 UTC, likeRewca commented on src/main/java/com/community/tools/service/slack/SlackHandlerService.java
> +              }else if (teamJoinPayload.getEvent().getText().equals("no")) {
прости я не понимаю, что ты имел ввиду

2020-10-04 07:32 UTC, pesua commented on src/main/java/com/community/tools/service/slack/SlackHandlerService.java
> +              }else if (teamJoinPayload.getEvent().getText().equals("no")) {
Код не отформатирован. Перед else должен быть пробел.

2020-10-04 07:34 UTC, pesua commented on src/main/java/com/community/tools/util/statemachie/actions/DidNotPassVerificationGitLogin.java
> +          "Lets try again! \nWrite your nike again.");
Только при ответе no или при написании любого не существующего гитхаб логина?

2020-10-04 07:36 UTC, pesua commented on src/main/java/com/community/tools/util/statemachie/actions/HideGuard.java
>        try {
Или отрефакторить сервисы чтоб они не плевались исключениями

2020-10-04 07:43 UTC, pesua commented on src/test/java/com/community/tools/util/statemachie/actions/AddGitNameActionTest.java
> +    addGitNameAction.execute(stateContext);
Не заметил что этот тест ожидает исключение, сорян. 
Но мне не кажется этот тест полезным, он проверяет что если одна из зависимостей кидает исключение то сервис тоже кинет исключение. От каких ошибок при разработке или рефакторинге тебя это защитит?

2020-10-04 08:56 UTC, likeRewca commented on src/main/java/com/community/tools/util/statemachie/actions/DidNotPassVerificationGitLogin.java
> +          "Lets try again! \nWrite your nike again.");
Смотри, во время перехода из состояние (там где ты вводишь логин в гит) в состояние проверки, запускается "защита"(класс HideGuard), т.е. это то событие без которого ивент не начнется пока не вернет true. Если такого ника нет в гите он оставляет false -> выводит сообщение "Такого нет гит ника в гите", и он будет вписывать ник пока не вернет true(т.е. найдет лигин в гите).
Этот класс конкретно вызывается в момент ответа на сообщение "No", т.е. тут ему сообщат, "ах если это не ты, введи логин вновь", и возвращает в состояние, когда он вписывал логин.

2020-10-05 11:06 UTC, likeRewca commented on src/main/java/com/community/tools/service/slack/SlackHandlerService.java
> +              }else if (teamJoinPayload.getEvent().getText().equals("no")) {
если бы тут за пробел не написал я бы не додумался об одной вещи)) а именно, если найдется особенный, который напишет, что то другое кроме да/нет

2020-10-07 08:10 UTC, pesua approved these changes
Добавь, пожалуйста, более понятные ключи для каналов и мерджи.

2020-10-07 08:10 UTC, pesua commented on src/main/java/com/community/tools/util/statemachie/actions/DidNotPassVerificationGitLogin.java
> +  @Value("${answeredNoDuringVerification}")
Ты добавил значение для этого поля в файле свойств?

Не могу добавить комент к старому обсуждению, напишу тут.
Верно ли я понял, что бот проверяет что ник существует а потом переспрашивает у пользователя "я нешал такого пользователя, это точно ты?"? Если да то было ли такое написанно в требованиях? Я сейчас не увидел этого. Это хорошо если тебе приходят идеи как сделать продукт лучше, но эти идеи сначала надо обсудить с продукт оунером, в данной ситуации с Лилей.

2020-10-07 08:10 UTC, pesua commented on src/main/java/com/community/tools/util/statemachie/actions/DidNotPassVerificationGitLogin.java
> +  @Value("${answeredNoDuringVerification}")
Нашел что добавил, ок.

2020-10-07 08:34 UTC, likeRewca commented on src/main/java/com/community/tools/service/PublishWeekStatsService.java
> +  @Value("${channel}")
я в проперти прописал вот так:
###Choose your channel###
channel=test_3
я могу комментарий поменять, если будет нужно

2020-10-07 08:37 UTC, likeRewca commented on src/main/java/com/community/tools/util/statemachie/actions/DidNotPassVerificationGitLogin.java
> +  @Value("${answeredNoDuringVerification}")
По поводу новых идей, я обсуждал любые предложения с Лилей и фразы которые будут отображаться при том или ином случае.

2020-10-07 08:41 UTC, pesua commented on src/main/java/com/community/tools/service/PublishWeekStatsService.java
> +  @Value("${channel}")
Мне из этого комента не становится понятнее что это за канал. Лучше давать понятные имена переменным чем писать к ним коменты.

2020-10-07 08:42 UTC, pesua commented on src/main/java/com/community/tools/util/statemachie/actions/DidNotPassVerificationGitLogin.java
> +  @Value("${answeredNoDuringVerification}")
Окей, если вы обсудили и приняли решение то отразите это в тикете, иначе ревьюеру кажется что задача сделана не по спеке. @Liliya-Stepanovna

2020-10-07 08:43 UTC, likeRewca commented on src/main/java/com/community/tools/util/statemachie/actions/DidNotPassVerificationGitLogin.java
> +  @Value("${answeredNoDuringVerification}")
окей

2020-10-07 08:45 UTC, likeRewca commented on src/main/java/com/community/tools/service/PublishWeekStatsService.java
> +  @Value("${channel}")
сейчас подумаю и исправлю

2020-10-07 13:51 UTC, merged