checkstyle_gitignore_convertUnicode
Broscorp-net/community-tools pull request #163
Opened 2020-09-24 00:10 UTC by marvintik

Обновлен checkstyle для проекта. Исправлены ошибки, которые нашел checkstyle. 
Добавлен класс, который конвертирует кириллические символы в Юникод для упрощения добавления и редактирования сообщений. Добавляет строчки, которые сконвертировал в property Spring`a для дальнейшего использования
Обновлен .gitignore. Исключает файлы Maven, Idea, Eclipse

2020-10-01 07:26 UTC, pesua requested changes
Славно, но есть лишние коменты. Если джавадок просто повторяет то же, что говорит имя метода, то такой джавадок это просто обуза. Он ничего не поясняет, но если при рефакторинге ты поменяешь параметры метода то придется еще и возиться-менять их в джавадоке. 
Пройдись, пожалуйста, по джавадокам, и удали те, которые не добавляют информации.

2020-10-01 07:26 UTC, pesua commented on pom.xml
> +    <dependency>
Что делает эта либа? Не вижу где она используется.

2020-10-01 07:26 UTC, pesua commented on src/main/java/com/community/tools/Application.java
> +   * Main method of Spring application.
Из кода это не ясно?) Коментарии нужно писать когда они **нужны**, иначе это груз, который тоже надо сапортить при развитии программы.

2020-10-01 07:26 UTC, pesua commented on src/main/java/com/community/tools/Application.java
> +            .properties(props())
А стандартные application.properties тоже подтянутся?

2020-10-01 07:26 UTC, pesua commented on src/main/java/com/community/tools/controller/GitHubController.java
> +   * @param state boolean variable, that shows pull request status
В документации как-раз было бы хорошо объяснить что значит true для пулреквеста, мне это не понятно.

2020-10-06 00:00 UTC, marvintik commented on pom.xml
> +    <dependency>
Она превращает все символы в строке в Юникод.

2020-10-06 16:49 UTC, marvintik commented on src/main/java/com/community/tools/Application.java
> +            .properties(props())
Да, подтягиваются и те, что в application.properties, и те, что добавили

2020-10-06 17:09 UTC, marvintik commented on src/main/java/com/community/tools/controller/GitHubController.java
> +   * @param state boolean variable, that shows pull request status
Переделала

2020-10-07 07:51 UTC, pesua commented on pom.xml
> +    <dependency>
Не нахожу место. Ткни меня носом, пожалуйста.

2020-10-07 07:54 UTC, pesua commented on pom.xml
> +    <dependency>
Нашел, эти террористы назвали пакет не так, как groupId

2020-10-07 07:55 UTC, pesua approved these changes
Неистово мерджить

2020-10-07 08:42 UTC, merged