transfet_stat_and_format_text
Broscorp-net/community-tools pull request #166
Opened 2020-10-03 00:27 UTC by marvintik

Переделан код, отправляющий еженедельную статистику. Создан метод, который отправляет блок текста в канал
Отредактирован текст, теперь он выводится в таком виде:
![message](https://user-images.githubusercontent.com/64403964/94978874-2e62f500-0528-11eb-8a74-75af6be14c70.png)

Ветка привязана к предыдущей во избежание конфликтов

2020-10-04 08:03 UTC, pesua commented
Не красиво, клиент не доволен.

2020-10-04 08:04 UTC, pesua requested changes
Не красиво, клиент не доволен. :Р

2020-10-04 12:11 UTC, marvintik commented
> Не красиво, клиент не доволен. :Р

Как переделать, чтоб было красиво?

2020-10-06 01:27 UTC, marvintik commented
> Не красиво, клиент не доволен. :Р
Теперь выглядит так. Лучше?
![Screenshot_1](https://user-images.githubusercontent.com/64403964/95148420-e9d79380-078b-11eb-9264-c1e793ae847e.png)

2020-10-07 08:12 UTC, pesua commented
Я так понял что эта ветка основывается на ветке с чекстайлом. Я сделаю ревью когда её смерджишь. Потыкай в меня палочкой когда сделаешь это, пожалуйста.

2020-10-07 08:43 UTC, marvintik commented
> Я так понял что эта ветка основывается на ветке с чекстайлом. Я сделаю ревью когда её смерджишь. Потыкай в меня палочкой когда сделаешь это, пожалуйста.

Смерджила, все хорошо

2020-10-27 08:51 UTC, closed without merging