Karma for comment
Broscorp-net/community-tools pull request #168
Opened 2020-10-13 14:00 UTC by likeRewca

resolve #105 
Начисление кармы происходит: при комментарии в pull request или в review комментарии (комментарии не в обсуждении кода).

2020-11-08 17:00 UTC, pesua requested changes

2020-11-08 17:00 UTC, pesua commented on src/main/java/com/community/tools/service/github/GitHubHookServlet.java
> +            .sendMessageToConversation(channel, "User " + user + " create a pull request \n url: " + url);
Тут грамматическая ошибка.

2020-11-08 17:00 UTC, pesua commented on src/main/java/com/community/tools/service/github/GitHubHookServlet.java
> +    boolean checkIssue =false;
Код недоформатирован.

2020-11-08 17:00 UTC, pesua commented on src/main/java/com/community/tools/service/github/GitHubHookServlet.java
> +    if (json.get("action").equals("created") && checkIssueAndComment(json)) {
isComment(json) && isIssue(json) было бы понятнее
Или hasComment и hasIssue. Кажется так точнее.

2020-11-08 17:00 UTC, pesua commented on src/main/java/com/community/tools/service/github/GitHubHookServlet.java
> +        json.getJSONObject("issue");
Как я понял - этот код расчитывает что если поля нет то будет брошено исключение. 
Использовать исключения для ветвления в программе это антипаттерн.
https://dzone.com/articles/exceptions-as-controlflow-in-java
https://softwareengineering.stackexchange.com/questions/189222/are-exceptions-as-control-flow-considered-a-serious-antipattern-if-so-why

2020-11-08 17:00 UTC, pesua commented on src/main/java/com/community/tools/model/StateEntity.java
>      public StateEntity() {
Давай переименуем эту штуку в юзера чтоб я больше не натуплялся.

2020-11-08 17:00 UTC, pesua commented on src/main/java/com/community/tools/service/github/KarmaService.java
> +  public void increaseKarmaForCommentApproved(String traineeReviewer) {
А когда понадобится метод для добавления кармы за реакцию на комент - придется делать еще один?
Лучше иметь один метод что удовлетворит оба кейса.

2020-11-09 18:45 UTC, likeRewca commented on src/main/java/com/community/tools/service/github/KarmaService.java
> +  public void increaseKarmaForCommentApproved(String traineeReviewer) {
Да, в ветке с реакцией я это исправил и сделал его более универсальным, но только имя забыл изменить.

2020-11-19 12:42 UTC, pesua approved these changes

2020-11-20 18:06 UTC, merged