add_points_labelled_done
Broscorp-net/community-tools pull request #169
Opened 2020-10-17 01:25 UTC by marvintik

Добавлен код, проверяющий добавление метки "done" к pull request. Если ее поставил ментор, то добавляет баллы за задания. Градация баллов осуществляется в отдельном метод. Если пользователь неправильно назвал пулл, не добавляет баллы. 
Если пользователь получил три метки "done", отправляет ему сообщение о возможности ревьюить коллегу.

2020-11-08 17:21 UTC, pesua requested changes

2020-11-08 17:21 UTC, pesua commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +      if (countService.getCountedCompletedTasks().get(creator).size() == 3) {
Почему три? Меня очень натупляет этот кусочек кода.

2020-11-08 17:21 UTC, pesua commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +  public int checkPoints(String pullName) {
Мне кажется этот метод не проверяет баллы а ищет и возврачает количество баллов. Давай назовем его соответствующе.

2020-11-08 17:21 UTC, pesua commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +    int number = tasksList.stream().filter(pullName::contains)
Очень неэффективно каждый раз парсить твою структуру конфига. Лучше сделать это один раз при инициализации сервиса и хранить в более удобном виде.

2020-11-08 17:21 UTC, pesua commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +      return 0;
Если в конфигах косяк - лучше не умалчивать об этом а браниться в лог, а еще лучше - падать, тогда есть шанс что кто-то это увидит.

2020-11-08 17:21 UTC, pesua commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +      e.getMessage();
Почему в одной ситуации код падает а в другой игнорирует?

2020-11-08 17:21 UTC, pesua commented on src/main/java/com/community/tools/service/github/GitHubHookServlet.java
> +                "INSERT INTO public.\"GitHookData\" (time, jsonb_data) VALUES ('"
Есть более удобные способы передавать параметры в запрос. Они, к тому же, защитят от инъекции. А тут есть уязвимость.

2020-11-08 17:21 UTC, pesua commented on src/main/resources/application.properties
> +pointsForTask = 1,2,2,3,3,3,2,4,4,3,5,5,4,5
Не удобно :/, есть еще идеи как это настраивать?

2020-11-08 17:21 UTC, pesua commented on src/test/java/com/community/tools/AddPointsTest.java
> +    assertEquals("labeled", json.get("action"));
Что проверяет этот и следующий асерт?

2020-11-10 03:22 UTC, marvintik commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +      if (countService.getCountedCompletedTasks().get(creator).size() == 3) {
Такое задание. Присылать сообщение после трех "done"

2020-11-10 03:23 UTC, marvintik commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +      return 0;
Это как раз проверка, что trainee правильно назвал пулл реквест. Если не правильно, то он просто не получает баллы.  У нас в правилах четко сказано, как нужно их называть.

2020-11-10 03:27 UTC, marvintik commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +      e.getMessage();
Тоже удивляло это, но так все сообщения в StateMachine Action отправляются. Просто взяла уже готовое наше решение.

2020-11-10 03:30 UTC, marvintik commented on src/main/java/com/community/tools/service/github/GitHubHookServlet.java
> +                "INSERT INTO public.\"GitHookData\" (time, jsonb_data) VALUES ('"
Я здесь просто перенесла на новую строчку часть запроса, чтоб не ругался checkstyle.

2020-11-10 03:32 UTC, marvintik commented on src/test/java/com/community/tools/AddPointsTest.java
> +    assertEquals("labeled", json.get("action"));
Мне нужно было проверить структуру  JSON в action "labeled" есть метка "done".

2020-11-10 07:39 UTC, marvintik commented on src/main/resources/application.properties
> +pointsForTask = 1,2,2,3,3,3,2,4,4,3,5,5,4,5
Переделала на Map. Удобней менять, добавлять значения и работать с содержимым

2020-11-10 07:39 UTC, marvintik commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +  public int checkPoints(String pullName) {
Убрала этот метод. После переделывания в Map он не нужен

2020-11-19 12:23 UTC, pesua commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +      return 0;
Обидно получается, давай хоть сообщение отправим что он - лошара.

2020-11-19 12:24 UTC, pesua commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +      return 0;
Просто я вангую что найдется человек, который сделает глупость, а потом будет приставать к нам, почему баллы не начислились.

2020-11-19 12:34 UTC, pesua requested changes

2020-11-19 12:34 UTC, pesua commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +      if (countService.getCountedCompletedTasks().get(creator).size() == 3) {
Да, но обычно в таких ситуациях выносят литерал в константу с именем, дающим понять что это за магическое число.

2020-11-19 12:34 UTC, pesua commented on src/main/java/com/community/tools/service/PointsTaskService.java
> +      e.getMessage();
Нутакое, лучше постараться понять почему так происходит. Давай тут ото всего падать.

2020-11-19 12:34 UTC, pesua commented on src/main/java/com/community/tools/service/github/GitHubHookServlet.java
> +                "INSERT INTO public.\"GitHookData\" (time, jsonb_data) VALUES ('"
Юдонандестенд, посмотри что такое sql injection, нельзя просто брать и конкатенировать строки для запроса.
Для этого есть jdbcTemplate.update(String sql, Object... args)

2020-11-19 12:34 UTC, pesua commented on src/test/java/com/community/tools/AddPointsTest.java
> +    assertEquals("labeled", json.get("action"));
Или я что-то упускаю, или тут читается джейсон из файла и проверяется что в нем есть поля, не понятно какой код этот тест проверяет.

2020-11-20 11:15 UTC, merged