Karma reaction
Broscorp-net/community-tools pull request #170
Opened 2020-10-18 19:59 UTC by likeRewca

Resolve #158 
Как только приходит ивент с меткой "done" запускается метод в карме (передается номер pr), если в этом pr есть комментарий с словом "approved" он проверяет наличие той или иной реакции (и владельца кто ставил реакцию). Если описанные условия выполняются, происходит зачисление балов.

2020-11-08 17:36 UTC, pesua requested changes

2020-11-08 17:36 UTC, pesua commented on src/main/java/com/community/tools/service/github/KarmaService.java
> +    for (GHReaction reaction : listOfReaction) {
У реакций есть таймстамп?

2020-11-08 17:36 UTC, pesua commented on src/main/java/com/community/tools/service/github/KarmaService.java
> +      e.printStackTrace();
Игнорировать исключение не правильно. А через такой вызов даже не всегда стектрейс в лог попадет.

2020-11-08 17:36 UTC, pesua commented on src/main/java/com/community/tools/service/github/KarmaService.java
> +        /*&& mentorsRepository.findByGitNick(actorOfReaction).isPresent()*/) {
Закоменченного кода быть не должно.

2020-11-08 17:36 UTC, pesua commented on src/main/java/com/community/tools/service/github/KarmaService.java
> +        changeKarmaForCommentApproved(usersComment, -1);
Имя метода говорит что он для случая когда кто-то апрувил.
Эта ветка не соответствует требованиям.

2020-11-08 17:36 UTC, pesua commented on src/main/java/com/community/tools/service/github/KarmaService.java
> +      usersComment = comment.getUser().getLogin();
Есть понятное всем слово "автор". ;)

2020-11-09 21:33 UTC, likeRewca commented on src/main/java/com/community/tools/service/github/KarmaService.java
> +    for (GHReaction reaction : listOfReaction) {
Да можно -> reaction.getCreatedAt().getTime();

2020-11-19 12:39 UTC, pesua approved these changes

2020-11-20 19:48 UTC, merged