Add questions about internship rules and channel information messages
Broscorp-net/community-tools pull request #172
Opened 2020-10-22 13:58 UTC by likeRewca

Resolve #160 и #154 
Этот пулл содержит 2 задания "Добавить сообщение с информацией о каналах" и "Ознакомить участника с правилами".

2020-11-08 19:26 UTC, pesua requested changes

2020-11-08 19:26 UTC, pesua commented on src/main/java/com/community/tools/model/StateEntity.java
> +    public void setFirstAnswer(String firstAnswer) {
Давайти через ломбок это все сделаем

2020-11-08 19:26 UTC, pesua commented on src/main/java/com/community/tools/model/StateEntity.java
> +    private String secondAnswer;
Спустя пол года ты сможешь вспомнить что это за ответы смотря на код?

2020-11-09 14:52 UTC, likeRewca commented on src/main/java/com/community/tools/model/StateEntity.java
> +    private String secondAnswer;
Я понял к чему ты ведешь. Лично для меня, то да я все еще буду помнить об этом (первая практика, первый небольшой опыт) + сам бот будет об этом напоминать (После того как он внесет гитник, в канал отправится сообщение с небольшой сводкой о человеке, включая и ответы на 3 вопроса). На счет других, кто возможно будет как-то его улучшать, то возможно 50/50(если увидели первый раз). Я понимаю, что имя должно отображать суть того, что в ней будет хранится, но тут трудно (для меня) было выбрать, или "Ответ на первый/второй/третий вопрос" или как-то назвать кратко изложенной сути вопроса "ответ на вопрос какой файл нельзя изменять". Но вопросы банально могут меняться и в этом случае нужно будет изменять имя переменной.
Пока переименовал в answerToFirstQuestion.

2020-11-19 12:36 UTC, pesua approved these changes

2020-11-20 05:50 UTC, merged