Split Messages to Bypass Embed Limits
Broscorp-net/community-tools pull request #296
Opened 2023-08-22 10:23 UTC by MaksymKalennyk

Content is divided into multiple parts to ensure the total character count stays within 6000 characters and 25 fields

2023-08-22 11:05 UTC, Larisa-Pomidor commented on message-service/src/main/java/com/community/tools/discord/DiscordMessageService.java
> +    for (int i = 0; i < fields.size(); i += 25) {
Может, вынести число 25 куда-то отдельно, например, в application.properties c понятным названием. Тем более, оно встречается не один раз.

2023-08-22 11:18 UTC, Kyrychenkozaurus requested changes

2023-08-22 11:18 UTC, Kyrychenkozaurus commented on message-service/src/main/java/com/community/tools/discord/DiscordMessageService.java
> +    Button button = Button.primary("buttonEmbed", "Button");
То есть кнопка будет дженерик кнопкой без функционала. Она ничего не принимает извне и за ней не закреплено ничего.

Я понимаю, что это задел на будущее, но как минимум имя кнопки ты мог бы принимать в метод. А еще лучше саму кнопку и просто инжектить её в эмбеддинг.

2023-08-22 11:18 UTC, Kyrychenkozaurus commented on message-service/src/main/java/com/community/tools/discord/DiscordMessageService.java
> +    TextChannel textChannel = jda.getTextChannelById(channelId);
Этот метод шлет embedded сообщение. Имя неточное.

Кроме того, имя параметра `MessageEmbed text` тоже неудачное. Я бы назвал `messageBody` или `messageText`. Многословность не порок, если она улучшает читабельность кода.

Почему этот метод protected?

2023-08-22 11:18 UTC, Kyrychenkozaurus commented on message-service/src/main/java/com/community/tools/discord/DiscordMessageService.java
> +public class DiscordMessageService {
`DiscordMessangingService` звучит чуть лучше и лучше отражает задачи сервиса.

2023-08-22 11:18 UTC, Kyrychenkozaurus commented on message-service/src/main/java/com/community/tools/discord/DiscordService.java
> +    this.jda = jda;
Зачем? @Autowired jda не работал?

2023-08-22 11:18 UTC, Kyrychenkozaurus commented on message-service/src/main/java/com/community/tools/discord/DiscordService.java
> +    DiscordMessageService discordMessageService = new DiscordMessageService(jda);
Вот это очень большая проблема. По факту ты делегировал спрингу создание синглтона DiscordMessageService, а затем проигнорировал его и создал собственный. На каждую сообщеньку которую ты пошлешь. Так делать нельзя, ты фактически игнорируешь все плюшки Спринга и создаешь место где мы потом будем ловить тонны багов.

DiscordMessageService должен инжектиться спрингом с помощью аннотации @Autowired.

2023-08-22 11:18 UTC, Kyrychenkozaurus commented on message-service/src/main/java/com/community/tools/discord/DiscordMessageService.java
> +    this.jda = jda;
Почему не просто
```
@Autowired
private JDA jda;
```

2023-08-23 11:41 UTC, Kyrychenkozaurus approved these changes

2023-08-23 11:41 UTC, Kyrychenkozaurus commented on message-service/src/main/java/com/community/tools/discord/DiscordMessagingService.java
> +  @Autowired private JDA jda;
Некрасиво.
Поле должно быть под аннотацией.

2023-08-23 15:38 UTC, Larisa-Pomidor approved these changes

2023-08-24 10:22 UTC, merged