implemented new ai-validation logic
Broscorp-net/community-tools pull request #323
Opened 2024-06-26 11:45 UTC by maxymmusiienko

2024-06-27 09:17 UTC, pesua requested changes

2024-06-27 09:17 UTC, pesua commented on bot/src/main/java/com/community/tools/service/discord/AiValidationCommand.java
> +    log.info("Processing ai validation command.");
В таких логах мало понту. Так, хібашо, дізнаєшся скільки раз запускалась команда. Якщо щось впаде то буде стек, тож цей лог не допомагає. 
Якщо вже логуєш треба додавати якусь інфу типу назви пула, юзера, айді меседжа. Щось що допоможе коли будеш шукати причину помилки.

2024-06-27 09:17 UTC, pesua commented on bot/src/main/java/com/community/tools/service/discord/AiValidationCommand.java
> +      log.info("Validation command used in the wrong channel");
ну це не інфо а ворнінг, тоді треба ще написати який зараз і який треба
де, взагалі, воно налаштовується?як так написати код шоб бути впевненим шо значення вірне?

2024-06-27 09:17 UTC, pesua commented on bot/src/main/java/com/community/tools/service/discord/AiValidationCommand.java
> +    if (!pulls.isEmpty()) {
а якщо там в черзі десять пулів лежать ти все одно раз на хвилину будеш процесити?

2024-06-27 09:17 UTC, pesua commented on bot/src/main/java/com/community/tools/service/discord/AiValidationCommand.java
> +      stdInput.lines().forEach(System.out::println);
сістем аут може не потрапити в логфайл, і як тоді це дебажити на віддаленому сервері?

2024-06-27 09:17 UTC, pesua commented on bot/src/main/python/ai-assistant.py
> +                                               - Shouldn't be overkill like threads"""
краще пояснити що є оверкіл

2024-06-27 09:17 UTC, pesua commented on bot/src/main/python/ai-assistant.py
> +from pr_agent import cli
ти, мабуть, локально встановив це через pip
як воно встановиться на сервері?

2024-06-27 09:26 UTC, maxymmusiienko commented on bot/src/main/java/com/community/tools/service/MessageListener.java
якби були б проблеми з чекстайлом то проєкт би не збілдився

2024-06-27 09:29 UTC, maxymmusiienko commented on bot/src/main/java/com/community/tools/service/discord/AiValidationCommand.java
> +      log.info("Validation command used in the wrong channel");
Це для того щоб запити на перевірку асистентом робились тільки в каналі для валідацій, канал цей задається по айді, ці айді є змінними оточення

2024-07-01 17:45 UTC, pesua approved these changes

2024-09-11 13:00 UTC, merged